version: '3.8'

services:
  web:
    build: .
    ports:
      - "8008:8008"
    environment:
      - ENV=production
      - PORT=8008
      - MONGODB_URI=mongodb+srv://princehkdigiverse_db_user:root123@cluster0.cwptqdg.mongodb.net/?appName=Cluster0
    volumes:
      - hk-media:/app/media
    restart: always

volumes:
  hk-media:
